server:
  port: 8081
spring:
  config:
    import:
      - aws-secretsmanager:${ENV}/${PROJECT_NAME}-backend-${REPO_NAME}/smtp
      - aws-secretsmanager:${ENV}/${PROJECT_NAME}-backend-${REPO_NAME}/s3
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
            http://localhost:9000
  datasource:
    url: ${DATABASE_URL:${database_url}}
    username: ${DATABASE_USERNAME:${AWS_RDS_SECRET_NAME:${database_username}}}
    password: ${DATABASE_PASSWORD:${database_password}}
    driver-class-name: ${DATABASE_DRIVER:com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME:${smtp_username}}
    password: ${SMTP_PASSWORD:${smtp_password}}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
app:
  application-name: Fanica
  base-url: http://localhost:8081
  login-page-url: http://localhost:9000/login
  s3:
    bucket-name: ${BUCKET_NAME:${bucket_name}}
    access-key: ${BUCKET_ACCESS_KEY:${bucket_access_key}}
    secret-key: ${BUCKET_SECRET_KEY:${bucket_secret_key}}
    base-url: ${BUCKET_ENDPOINT:${bucket_endpoint}}
    region: ${AWS_REGION}
    storage-class: STANDARD